"use client";

import Link from "next/link";
import { useState } from "react";

type User = { id: number; email: string; name: string | null };

type DashboardProps = {
  users: User[];
  initialView?: string;
  signedInEmail?: string | null;
  onSignIn: () => Promise<void>;
  onSignOut: () => Promise<void>;
};

const modulePages: Record<string, { label: string; title: string; description: string; action: string; stats: string[][]; heading: string; columns: string[]; rows: string[][] }> = {
  Transactions: { label: "Accounts receivable", title: "Transactions", description: "Review and manage every business transaction in one place.", action: "New transaction", stats: [["Total transactions", "128", "Up 12 this month"], ["Total volume", "$584,210", "Up 18.4% this period"], ["Pending review", "7", "3 need attention"]], heading: "Transaction register", columns: ["Transaction", "Customer", "Date", "Status", "Amount"], rows: [["INV-1051", "Northstar Co.", "Sep 03, 2026", "Pending", "$5,800.00"], ["INV-1050", "Juniper & Co.", "Sep 02, 2026", "Paid", "$3,250.00"], ["INV-1049", "Vertex Labs", "Sep 01, 2026", "Overdue", "$1,890.00"]] },
  Sales: { label: "Sales pipeline", title: "Sales", description: "Track opportunities from first contact to closed deal.", action: "New opportunity", stats: [["Pipeline value", "$248,600", "Up 14.2% this month"], ["Open opportunities", "32", "8 added this week"], ["Win rate", "68%", "Up 6.4% vs. last month"]], heading: "Active opportunities", columns: ["Opportunity", "Account owner", "Stage", "Expected close", "Value"], rows: [["Website redesign", "Northstar Co.", "Proposal", "Sep 18, 2026", "$42,000"], ["Brand refresh", "Lumina Studio", "Negotiation", "Sep 24, 2026", "$18,500"], ["Analytics setup", "Vertex Labs", "Discovery", "Oct 02, 2026", "$27,800"]] },
  Invoices: { label: "Accounts receivable", title: "Invoices", description: "Create, send, and follow up on every invoice.", action: "Create invoice", stats: [["Total outstanding", "$19,430", "7 invoices due this week"], ["Paid this month", "$64,860", "Up 11.8% vs. August"], ["Overdue", "$1,890", "1 invoice needs attention"]], heading: "Invoice register", columns: ["Invoice", "Customer", "Issued", "Due date", "Status", "Amount"], rows: [["INV-1051", "Northstar Co.", "Sep 03, 2026", "Oct 03, 2026", "Pending", "$5,800.00"], ["INV-1050", "Juniper & Co.", "Sep 02, 2026", "Oct 02, 2026", "Paid", "$3,250.00"], ["INV-1049", "Vertex Labs", "Sep 01, 2026", "Sep 15, 2026", "Overdue", "$1,890.00"]] },
  Inventory: { label: "Stock control", title: "Inventory", description: "Know what is available, reserved, and running low.", action: "Add item", stats: [["Inventory value", "$126,840.50", "412 total items"], ["In stock", "394", "95.6% healthy stock"], ["Low stock", "18", "4 items need reorder"]], heading: "Item catalogue", columns: ["SKU", "Item", "Category", "On hand", "Reorder point", "Status"], rows: [["SKU-2204", "Canvas Tote", "Accessories", "12", "25", "Low stock"], ["SKU-1140", "Desk Organizer", "Office", "86", "30", "In stock"], ["SKU-3341", "Travel Mug", "Accessories", "44", "20", "In stock"]] },
  Customers: { label: "Relationship management", title: "Customers", description: "Keep customer records and account activity in one place.", action: "Add customer", stats: [["All customers", "284", "Up 38 this month"], ["Active accounts", "218", "76.8% of customer base"], ["Average value", "$4,280", "Up 9.2% this quarter"]], heading: "Customer directory", columns: ["Customer", "Industry", "Last activity", "Open invoices", "Lifetime value"], rows: [["Northstar Co.", "Technology", "Today, 09:42", "1", "$42,800"], ["Lumina Studio", "Creative services", "Yesterday", "0", "$31,240"], ["Vertex Labs", "Technology", "Sep 01, 2026", "1", "$28,900"]] },
  Settings: { label: "Workspace administration", title: "Settings", description: "Manage your workspace preferences and account defaults.", action: "Save changes", stats: [["Workspace", "Mini NetSuite", "Practice environment"], ["Currency", "USD ($)", "Default transaction currency"], ["Time zone", "UTC +09:00", "Japan Standard Time"]], heading: "Workspace preferences", columns: ["Preference", "Current value", "Description"], rows: [["Company name", "Mini NetSuite", "Shown on invoices and reports"], ["Default payment terms", "Net 30", "Applied to new invoices"], ["Fiscal year starts", "January", "Used for reporting periods"]] },
};

const navItems = [["Overview", "▦"], ["Sales", "↗"], ["Invoices", "▤"], ["Inventory", "◫"], ["Customers", "◎"], ["Settings", "⚙"]];

export default function Dashboard({ users, initialView = "Overview", signedInEmail, onSignIn, onSignOut }: DashboardProps) {
  const [view] = useState(initialView);
  const [toast, setToast] = useState("");
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2400); };
  const page = modulePages[view];

  return (
    <div className="app-shell">
      <aside className="sidebar" aria-label="Main navigation">
        <div className="brand"><span className="brand-mark">N</span><span>mini<span className="brand-accent">/</span>netsuite</span></div>
        <p className="eyebrow">Workspace</p>
        <nav className="nav-list">{navItems.map(([label, icon]) => <Link key={label} href={label === "Overview" ? "/" : `/${label.toLowerCase()}`} className={`nav-item ${view === label ? "active" : ""}`}><span className="nav-icon">{icon}</span>{label}</Link>)}</nav>
        <div className="sidebar-bottom">
          <div className="support-card"><span className="status-dot" /><div><strong>All systems good</strong><small>Last synced 2 min ago</small></div></div>
          <div className="profile"><span className="avatar">{signedInEmail ? "AM" : "--"}</span><div><strong>{signedInEmail ? "Alex Morgan" : "Guest user"}</strong><small>{signedInEmail ? "Administrator" : "Not signed in"}</small></div><span className="more">•••</span></div>
        </div>
      </aside>
      <main className="main-content">
        <header className="topbar"><div className="mobile-brand"><span className="brand-mark">N</span>mini/netsuite</div><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>{view}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Search">⌕</button><button className="icon-button notification" aria-label="Notifications">♧<i /></button><span className="top-avatar">AM</span></div></header>
        {view === "Overview" ? <Overview onNotify={notify} users={users} /> : <ModuleView page={page} onNotify={notify} />}
        <footer>Mini NetSuite <span>•</span> Learning project <span>•</span> Data shown is for practice <span>•</span>{signedInEmail ? <button className="text-button" onClick={onSignOut}>Sign out</button> : <button className="text-button" onClick={onSignIn}>Sign in</button>}</footer>
      </main>
      <div className={`toast ${toast ? "visible" : ""}`} role="status">{toast}</div>
    </div>
  );
}

function Overview({ onNotify, users }: { onNotify: (message: string) => void; users: User[] }) {
  return <>
    <section className="page-intro"><div><p className="eyebrow">Thursday, September 03, 2026</p><h1>Good morning, Alex<span className="accent-dot">.</span></h1><p className="muted">Here&apos;s what&apos;s happening across your business today.</p></div><Link className="primary-button" href="/transactions/new"><span>+</span> New transaction</Link></section>
    <section className="metric-grid" aria-label="Business metrics"><Metric label="Net revenue" value="$84,290" note="Compared to $74,720 last month" trend="Up 12.8%" className="revenue" /><Metric label="Open invoices" value="24" note="7 due this week" trend="Up 4.2%" /><Metric label="Inventory value" value="$126,840.50" note="412 total items · 18 low stock" trend="Down 2.1%" negative /><Metric label="New customers" value={String(Math.max(38, users.length))} note="Since the start of this month" trend="Up 8.6%" /></section>
    <section className="content-grid"><article className="panel sales-panel"><div className="panel-heading"><div><p className="eyebrow">Performance</p><h2>Revenue overview</h2></div><select aria-label="Revenue period"><option>Last 7 months</option><option>Last 30 days</option></select></div><div className="chart-summary"><strong>$584,210</strong><span className="trend positive">Up 18.4%</span><small>vs. previous period</small></div><div className="chart"><div className="chart-grid"><span>$100k</span><span>$75k</span><span>$50k</span><span>$25k</span><span>$0</span></div><svg viewBox="0 0 700 220" preserveAspectRatio="none" aria-label="Revenue rises from April through October"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#d8efe9" stopOpacity=".8" /><stop offset="1" stopColor="#d8efe9" stopOpacity="0" /></linearGradient></defs><path className="area" d="M0 174 C60 160 80 162 120 145 S190 152 230 124 S295 136 345 108 S405 106 460 82 S525 92 570 55 S635 66 700 20 V220 H0Z" /><path className="line" d="M0 174 C60 160 80 162 120 145 S190 152 230 124 S295 136 345 108 S405 106 460 82 S525 92 570 55 S635 66 700 20" /></svg><div className="chart-labels"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span><span>Oct</span></div></div></article><article className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">Live feed</p><h2>Recent activity</h2></div><button className="text-button" onClick={() => onNotify("Showing all activity")}>View all <span>→</span></button></div><div className="activity-list">{[["↗", "Payment received", "INV-1048 · Lumina Studio", "+$2,400", "teal"], ["▤", "Invoice sent", "INV-1051 · Northstar Co.", "2h ago", "yellow"], ["◎", "New customer added", "Marcel Chen", "4h ago", "blue"], ["◫", "Stock alert", "SKU-2204 · Canvas Tote", "Low stock", "coral"]].map(([icon, title, detail, time, color]) => <div className="activity-item" key={title}><span className={`activity-icon ${color}`}>{icon}</span><div><strong>{title}</strong><p>{detail}</p></div><time>{time}</time></div>)}</div></article></section>
    <section className="panel transactions-panel"><div className="panel-heading"><div><p className="eyebrow">Accounts receivable</p><h2>Recent transactions</h2></div><button className="text-button" onClick={() => onNotify("Showing all transactions")}>View all <span>→</span></button></div><div className="table-wrap"><table><thead><tr><th>Transaction</th><th>Customer</th><th>Date</th><th>Status</th><th className="amount">Amount</th></tr></thead><tbody>{[["INV-1051", "Product design retainer", "Northstar Co.", "Pending", "$5,800.00"], ["INV-1050", "Q3 marketing services", "Juniper & Co.", "Paid", "$3,250.00"], ["INV-1049", "Annual software license", "Vertex Labs", "Overdue", "$1,890.00"]].map(([id, name, customer, status, amount]) => <tr key={id}><td><span className="transaction-id">{id}</span><strong>{name}</strong></td><td>{customer}</td><td>Sep 03, 2026</td><td><span className={`pill ${status.toLowerCase()}`}>{status}</span></td><td className="amount">{amount}</td></tr>)}</tbody></table></div></section>
  </>;
}

function Metric({ label, value, note, trend, negative, className = "" }: { label: string; value: string; note: string; trend: string; negative?: boolean; className?: string }) { return <article className={`metric-card ${className}`}><div className="card-label"><span>{label}</span><span className={`trend ${negative ? "negative" : "positive"}`}>{trend}</span></div><strong>{value}</strong><small>{note}</small></article>; }

function ModuleView({ page, onNotify }: { page: (typeof modulePages)[string]; onNotify: (message: string) => void }) { const section = page.title.toLowerCase(); const actionPath = page.title === "Settings" ? `/${section}/edit` : `/${section}/new`; return <><section className="page-intro module-intro"><div><p className="eyebrow">{page.label}</p><h1>{page.title}<span className="accent-dot">.</span></h1><p className="muted">{page.description}</p></div><Link className="primary-button" href={actionPath}><span>+</span> {page.action}</Link></section><section className="metric-grid module-metrics">{page.stats.map(([label, value, note]) => <Metric key={label} label={label} value={value} note={note} trend="●" />)}</section><section className="panel module-table"><div className="panel-heading"><div><p className="eyebrow">{page.label}</p><h2>{page.heading}</h2></div><button className="text-button" onClick={() => onNotify("Export started")}>Export <span>↓</span></button></div><div className="table-wrap"><table><thead><tr>{page.columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{page.rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td className={index === row.length - 1 ? "amount" : ""} key={`${row[0]}-${cell}`}>{["Pending", "Paid", "Overdue", "Low stock", "In stock"].includes(cell) ? <span className={`pill ${cell.toLowerCase().replace(" ", "-")}`}>{cell}</span> : cell}</td>)}</tr>)}</tbody></table></div>{page.title === "Settings" && <div className="settings-options">{["Email notifications", "Compact table view", "Two-step approval"].map((label, index) => <label key={label}><span><strong>{label}</strong><small>{index === 0 ? "Receive updates about invoices and stock alerts" : index === 1 ? "Show more records in less space" : "Require approval before sending invoices"}</small></span><input type="checkbox" defaultChecked={index === 0} onChange={(event) => onNotify(`${event.target.checked ? "Enabled" : "Disabled"} setting`)} /></label>)}</div>}</section></>; }